name = "Mofos Pack"
author = "Mofo"
version = "3.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7eb6b0a263d4f3a9094dc35bee1d498435e7fba3b92d30719f9488a8ab32800"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
