name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "701b48eb4bb4fa24e030206110cf26647910df09f582fce83e7181584ca8290b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
