name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30e8ae38a150f32c709ecb6788a7614e8f71c8f6413ee4b89e2cf159ebb22c93"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
