name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c65484b7664d49b028b91c9e37ff8e99a41e8bc0a5daafe654bee6d8d33b7a19"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
