name = "Mofos Pack"
author = "Mofo"
version = "3.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "910afbb4655e165f26827eb9a3184b4ca6298c044290e1dcde311d1cb512b9aa"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
