name = "Mofos Pack"
author = "Mofo"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10a69c475b5cbbedc88bab9d3a74ae1cf6705fce3d90aae681a13a18fce7754d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
