name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "379525bd7def3e008dc9483a899394fba5349cf16c3c6d9bddf1fb0a26bef9b6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
