name = "Mofos Pack"
author = "Mofo"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a89dfb3ae0b4fbd8998dd4feaf470c4140f16dff7ab4778fd6cc284c0ffa5e27"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
