name = "Mofos Pack"
author = "Mofo"
version = "3.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "defb13bc4e2ced3d6ff654f7e5077bd111961af43d78947a07b0216239095441"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
