name = "Mofos Pack"
author = "Mofo"
version = "3.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd4771222993a45ed90ce21cc586667b3f5db0cd3a02d8ac27b6cd32c61c00d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
