name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04903eb55e07f91c0dd339fd1d61a3c39c1cc8273cc80611a0fcf5e3a17fb7fc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
