name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "764e08c57b2fc81db23c3f47f43c25dde985e3e72f1b75d746cfa78461602fa0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
