name = "Mofos Pack"
author = "Mofo"
version = "3.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e38bd6354a8f3e631665d39a339ac99ca72b330b788e17737666752d0b1a6ed"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
