name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b3d084a9ce3feb35c13fe112b17fa5194f73f7b96ed076245e1c47cb3ca026a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
