name = "Mofos Pack"
author = "Mofo"
version = "3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6152a65a07140359df0cc42750ec6038d113d573deff8171ece04b9b59c92fa8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
