name = "Mofos Pack"
author = "Mofo"
version = "3.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50c2efb17963dd4b07b54898a663c4e4cc3481c4f3f41970a6dbfe51e2d04499"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
