name = "Mofos Pack"
author = "Mofo"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdf17f53034e08fe21cc2594b8b0bd5456ed8c31310e322ed0354fcd687b177c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
