name = "Mofos Pack"
author = "Mofo"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "807624165f2eaa9b37edf878bf659b176e668bfbe0cd3eca9d3afd171c3416a8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
